---

image: maven:3.8-openjdk-17-slim

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  script:
    - mvn ${MAVEN_CLI_OPTS} clean install
    - cat README.md | mvn exec:java -Dexec.mainClass=com.marlo.quickcheck.ExampleApp
  artifacts:
    paths:
      - target

pages:
  stage: deploy
  only:
    refs:
      - master
  except:
    - tags
  script:
    - mv target/site public
  artifacts:
    paths:
      - public
      - target/*.jar
